scala_specs2_junit_test(
    name = "poc",
    size = "small",
    srcs = glob(["*.scala"]),
    deps = [
        "//poc/src/main/scala/org/midityping/poc:poc",
        "//poc/src/main/scala/org/midityping/poc/midi:midi",
    ],
    resources = ["//poc/src/test/resources:test-deps"],
    suffixes = ["Test"],
)
