scala_library(
    name = "actions",
    srcs = glob(["*.scala"]),
    deps = [
        "//poc/src/main/scala/org/midityping/poc/common",
        "//poc/src/main/scala/org/midityping/poc/actions/awt",
        "//poc/src/main/scala/org/midityping/poc/logging",
        "@org_slf4j__slf4j_api//jar",
    ],
    visibility = ["//visibility:public"],
)
