scala_specs2_junit_test(
    name = "awt",
    size = "small",
    srcs = glob(["*.scala"]),
    deps = [
        "//poc/src/main/scala/org/midityping/poc/actions/awt",
    ],
    suffixes = ["Test"],
)
