scala_library(
    name = "events",
    srcs = glob(["*.scala"]),
    deps = [
        "//poc/src/main/scala/org/midityping/poc/common",
        "//poc/src/main/scala/org/midityping/poc/logging",
        "@org_slf4j__slf4j_api//jar:jar",
    ],
    visibility = ["//visibility:public"]
)
