scala_library(
    name = "mapping",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
        "//poc/src/main/scala/org/midityping/poc/common",
        "//poc/src/main/scala/org/midityping/poc/events",
        "//poc/src/main/scala/org/midityping/poc/actions",
    ],
)
