scala_library(
    name = "storage",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
        "//poc/src/main/scala/org/midityping/poc/mapping",
        "//poc/src/main/scala/org/midityping/poc/actions",
        "@com_google_code_gson__gson//jar",
    ],
)
