scala_library(
    name = "storage",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
        "//poc/src/main/scala/org/midityping/poc/mapping",
        "//poc/src/main/scala/org/midityping/poc/actions",
        "//poc/src/main/scala/org/midityping/poc/events",
    ],
)
