scala_specs2_junit_test(
    name = "actions",
    size = "small",
    srcs = glob(["*.scala"]),
    deps = [
        "//poc/src/main/scala/org/midityping/poc/common",
        "//poc/src/main/scala/org/midityping/poc/events",
        "//poc/src/main/scala/org/midityping/poc/actions",
        "//poc/src/test/scala/org/midityping/poc/testsupport",
    ],
    suffixes = ["Test"],
)
