scala_library(
    name = "system",
    srcs = glob(["*.scala"]),
    deps = [
        "//poc/src/main/scala/org/midityping/poc/actions",
        "//poc/src/main/scala/org/midityping/poc/events",
        "//poc/src/main/scala/org/midityping/poc/mapping",
        "//poc/src/main/scala/org/midityping/poc/mapping/storage",
        "@org_slf4j__slf4j_api//jar",
    ],
    visibility = ["//visibility:public"]
)