scala_library(
    name = "system",
    srcs = glob(["*.scala"]),
    deps = [
        "//poc/src/main/scala/org/midityping/poc/actions",
        "//poc/src/main/scala/org/midityping/poc/events",
        "//poc/src/main/scala/org/midityping/poc/mapping",
        "@com_google_code_gson__gson//jar",
    ],
    visibility = ["//visibility:public"]
)