scala_library(
  name = "poc",
  srcs = glob(["*.scala"]),
  visibility = ["//visibility:public"],
  deps = [
      "@com_fasterxml_jackson_core__jackson_databind//jar",
      "@com_fasterxml_jackson_core__jackson_annotations//jar",
      "@com_fasterxml_jackson_core__jackson_core//jar",
      "@com_fasterxml_jackson_module__jackson_module_scala//jar",
  ]
)
