scala_library(
    name = "testsupport",
    srcs = glob(["*.scala"]),
    deps = [
        "//poc/src/main/scala/org/midityping/poc/common",
        "//poc/src/main/scala/org/midityping/poc/events",
    ],
    visibility = ["//visibility:public"]
)