
scala_specs2_junit_test(
    name = "poc",
    size = "small",
    srcs = glob(["*.scala"]),
    deps = [
      "//poc/src/main/scala/org/midityping/poc/midi",
      "//poc/src/main/scala/org/midityping/poc/events"
    ],
    suffixes = ["IT"],
)