scala_library(
    name = "midi",
    srcs = glob(["*.scala"]),
    deps = [
        "//poc/src/main/scala/org/midityping/poc/common:common",
        "//poc/src/main/scala/org/midityping/poc/events:events",
        "//poc/src/main/scala/org/midityping/poc/logging",
        "@org_slf4j__slf4j_api//jar",
  ],
    visibility = ["//visibility:public"]
)
