#scala_library(
#  name = "midityping",
#  srcs=["Poc.scala"]
#)

scala_specs2_junit_test(
    name = "PocTest",
    size = "small",
    srcs = ["PocTest.scala"],
    deps = [],
    suffixes = ["Test"],
)